### ISSUE TITLE
Add line numbers to Catch somehow

### ISSUE THREAD

**Issue by josharian** [dsnet/try#2]
I just started using this, and I already want line numbers. :)

**Comment by josharian** [comment]
`t.Fatalf("%s:%d: %v", file, line, err)`

**Comment by josharian** [comment]
The normal (non-helper) case is harder. We could pass a context to each of the func handlers that contains file, line, and error?

**Comment by josharian** [comment]
For the general case, we could do:

```go
func Recover(err *error, handlers ...any)
```

where the handlers could be either `func()` or `func(runtime.Frame)`. If the latter, it is called with the `runtime.Frame` from which the error was recovered.

This would then make it easy to implement the `testing` and `log` helpers (even out of package, which is a good sign).

But I don't love `...any`. Ideas?

**Comment by dsnet** [comment]
Bad idea 1:
```go
func Recover[F interface{ func() | func(runtime.Frame) }](err *error, handlers ...F)
```

Bad idea 2:
```go
func Recover(err *error, handlers ...func())
func RecoverFrame(err *error, handlers ...func(runtime.Frame))
```

**Comment by josharian** [comment]
RecoverFrame seems OK. I'll implement that and see how it plays.

**Comment by dsnet** [comment]
It was somewhat of a hack that handle is a variadic argument since you almost always ever have zero or one handlers.

We could do:
```go
func Recover(*error)
func RecoverF(*error, func())
func RecoverFrame(*error, func(runtime.Frame))
```

**Comment by josharian** [comment]
At least for the TB and Fatal (and Log?) helpers, you don't even need the `*error` argument. The error will be handled entirely by the func, not returned by the containing func.

That suggests a general purpose:

```go
func Recover(*error, func(runtime.Frame))
```

and then a few use-case specific variants:

```go
func Handle(*error)
func HandleF(*error, func())
func TB(tb *testing.TB)
func Fatal() // maybe the wrong name?
func Log()
```

All of which could be implemented in terms of Recover:

```go
func Handle(ptr *error) {
  Recover(ptr, nil)
}
```

```go
func HandleF(ptr *error, fn func()) {
  Recover(ptr, func(runtime.Frame) { fn() } )
}
```

```go
func TB(tb testing.TB) {
  var err error
  Recover(&err, func(f runtime.Frame) {
    tb.Fatalf("%s:%d: %v", f.File, f.Line, err)
  })
}
```

```go
func Fatal(tb testing.TB) {
  var err error
  Recover(&err, func(f runtime.Frame) {
    log.Fatalf("%s:%d: %v", f.File, f.Line, err)
  })
}
```

```go
func Log(tb testing.TB) {
  var err error
  Recover(&err, func(f runtime.Frame) {
    log.Printf("%s:%d: %v", f.File, f.Line, err)
  })
}
```

(All that code written directly into GitHub, view with suspicion.)
