### ISSUE TITLE
Rename Catch to Handle?

### ISSUE THREAD

**Issue by josharian** [dsnet/try#3]
I keep second-guessing myself...should this be called Handle? (I don't think we have any backwards compat yet. There's a 72 hour grace period for all new Go APIs.)

**Comment by dsnet** [comment]
We haven't even made a tagged release. So now's the perfect time to make breaking changes.

> should this be called Handle?

SGTM. I was being cute and named it "catch" since "try" and "catch" go together in many other languages (ahem. Java).

**Comment by dsnet** [comment]
Want to send a PR for this?

**Comment by josharian** [comment]
Hi. I'm being crazy. But I made the PR and now I'm wondering whether it ought to be called Recover. That'd make it way more obvious how it is to be used--must be deferred, must be up in the call stack somewhere, etc.

**Comment by dsnet** [comment]
I'm fine with `Recover`, `Handle`, or `Catch`. Just stop adding more letters ;)
* `Catch` => 5 letters
* `Handle` => 6 letters
* `Recover` => 7 letters

**Comment by josharian** [comment]
`OhNoStop`, `DontPanic`, `CatchPanic`, `HandlePanic`, `RecoverPanic`...`IUsedThisAPIForConvenienceAndAllIGotWasSomeLousyRSIAndAJavaHangover`. I could go on all day.

**Comment by josharian** [comment]
I'm leaning towards Recover. I'll use it a bit a see how it looks.
