### ISSUE TITLE
Use short file name?

### ISSUE THREAD

**Issue by dsnet** [dsnet/try#5]
This snippet:
```go
func main() {
	defer F(log.Fatal)
	E(io.EOF)
}
```
prints:
```
2022/05/05 13:39:00 /tmp/sandbox911101128/main.go:13: EOF
```

The full path name is somewhat of mouthful, perhaps we should just use the short file name?
```
2022/05/05 13:39:00 main.go:13: EOF
```

This would similar to how the `log` package does it: https://cs.opensource.google/go/go/+/refs/tags/go1.18.1:src/log/log.go;l=149-158;drc=0e90ba933565ab6e719d6981d8d6195e06625f47

\cc @josharian

**Comment by josharian** [comment]
Fine by me.

**Comment by dsnet** [comment]
It's unfortunate that we have duplicate spam. When doing:
```go
func Test(t *testing.T) {
	defer F(t.Fatal)
	E(io.EOF)
}
```
This prints:
```
try.go:176: /tmp/sandbox911101128/main_test.go:13: EOF
```

I'm going to be so tired of seeing `try.go:176` after a few years 😆

**Comment by josharian** [comment]
We could put `F` in its own file and then use line directives to print all kinds of exciting things.

/me ducks
